### ISSUE TITLE
Issues in tutorials, code runs, but generated data are empty

### ISSUE THREAD

**Issue by spiacquadio** [gerlero/openfoam-app#137]
First of all, thank you very much for this effort!

I was trying to run a couple of tutorials and always incur the same issues.  When using the Allrun command, it seems to compile and data are generated. These are however empty. The command foamToVTK runs and data are generated but they are basically empty and when opening the files in Paraview nothing happens, i.e. no file appears on the left side and of course no apply button is available.

I also tried to run separately the blockMesh command and then run (e.g. via potentialFoam for the cylinder tutorial). In this case I get the following log: 

Create time
Create mesh for time = 0
potentialFlow: Operating solver in PISO mode
Reading velocity field U
--> FOAM FATAL ERROR: (openfoam-2212)
cannot find file "/Users/spiacqua/Documents/OpenFoam/tutorials/basic/potentialFoam/cylinder/0/U"

    From virtual Foam::autoPtr<Foam::ISstream> Foam::fileOperations::uncollatedFileOperation::readStream(Foam::regIOobject &, const Foam::fileName &, const Foam::word &, const bool) const
    in file global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C at line 561.

FOAM exiting

I created a folder 0 to solve the issue and the code ran, but still, the data created are basically empty.
Any clue why that might happen? I must say, I'm not that familiar yet.
I'm running on a MacBook Pro M2 Max.

Thanks in advance

**Comment by gerlero** [comment]
I don't see a noticeable difference in behavior between running the case with the app and the official Linux version of OpenFOAM (via Docker). I see a couple of warnings but they seem to show up in both...

Could you list the steps that lead to the issue specifically? I didn't test `foamToVTK` as I'm not familiar with it, yet I'm able to load up the case in ParaView just fine (e.g. with ``paraFoam -builtin`` + maybe click of "reload files" required).

**Comment by gerlero** [comment]
> [log.potentialFoam.zip](https://github.com/gerlero/openfoam-app/files/11517414/log.potentialFoam.zip)

Thanks! Looks functionally identical to what I saw when I tried it.

> ```paraview: command not found```

Could it be that you haven't installed ParaView with Homebrew, so the `paraview` command isn't available? If so, you could do ``paraFoam -builtin -touch`` instead which should create a `.foam` file in the case directory that can be directly opened with ParaView. That should let you view the case in ParaView.

Again, I can't really say that there's no problem with `foamToVTK` and this case (I'm not familiar enough with it and can't really tell from the VTK directory you attached) , but if all you want is to visualize the results then the `-touch`/`.foam` file approach might be what you need.

**Comment by spiacquadio** [comment]
That was, weirdly enough the issue. I re-installed Paraview via Homebrew (I had Paraview already on the machine because of the use with FeniCS). Now both using `paraFoam` or `foamToVTK` delivers the results properly and the visualization is as expected.
Thank you very much for the help and again for creating this native version for Apple Silicon!
