### ISSUE TITLE
Change OpenFOAM shell session

### ISSUE THREAD

**Issue by GooseofEast** [gerlero/openfoam-app#153]
I think the layout of the OpenFOAM default shell's upper path and lower commands without color differentiation is unclear. How can I get the default zsh shell's configuration after activating the OpenFOAM environment like this:
usr@MBP: (green bold) current path(blue bold) %

**Comment by gerlero** [comment]
BTW, a simpler option might be to just [override the Bash prompt](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html) once you've entered the shell session.

**Comment by GooseofEast** [comment]
> BTW, a simpler option might be to just [override the Bash prompt](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html) once you've entered the shell session.

**Comment by GooseofEast** [comment]
Thank you for your reply and reminder.
