### ISSUE TITLE
Errors in residual monitoring

### ISSUE THREAD

**Issue by AlexChy829** [gerlero/openfoam-app#257]
Greetings! I am a beginner in OpenFOAM and would like to ask you about the error reported by foamMonitor, the residual file monitored and the problems encountered are as follows. The device is a MacBookAir M2, the latest version of gnuplot is installed via homebrew, the terminal mode is qt. Thank you so much!!!
![residual monitoring error](https://github.com/gerlero/openfoam-app/assets/69065828/3479b6f6-04eb-47dd-a2c3-d2ba4bdd70ee)
[solverInfo.txt](https://github.com/gerlero/openfoam-app/files/14960059/solverInfo.txt)
@gerlero

**Comment by gerlero** [comment]
Sorry, I'm not that familiar with the `foamMonitor` utility. Is there any way you can try running the same case on a Linux version of OpenFOAM to confirm that the behavior is different from that on macOS?

**Comment by gerlero** [comment]
Closing. Feel free to reopen if needed.
