### ISSUE TITLE
Error: Failed to mount the OpenFOAM-v2306 volume

### ISSUE THREAD

**Issue by bdlabitt** [gerlero/openfoam-app#263]
After yesterday getting a successful CfdOF run using HiSA (for the first time), I find that today I can't mount OpenFOAM at all.
Either by clicking on the OpenFOAM app installed, or typing % openfoam2306.  The error I get on the console is:
`% /Applications/OpenFOAM-v2306.app/Contents/Resources/etc/openfoam
---------------------------------------------------------------------------
             |                                                             
   ( )       |                 °°° OpenFOAM-v2306.app °°°                  
  ( )    ( ) |                                                             
      ( )    | Native OpenFOAM for macOS                             
             | https://github.com/gerlero/openfoam-app                 
---------------------------------------------------------------------------
Mounting the OpenFOAM-v2306 volume...
ERROR: Failed to mount the OpenFOAM-v2306 volume`

Umm, how can this be fixed?  Maybe coincidentally, a "transparent" update occurred this afternoon.  I found a restore.log under /System/Volumes/Update that was dated today.  But the log didn't contain anything to do with OpenFOAM.

About the only thing I can think of is I did not exit the shell before rebooting the computer (network issue of some sort).  Any guidance would be greatly appreciated!

**Comment by bdlabitt** [comment]
brew doctor is showing some kegs with no formulae, python-pyparsing, python-kiwisolver, python-cycler, python-brotli.  There's also a warning of python-dateutil being deprecated or disabled.  Also some unexpected dylibs in /usr/local/lib, but they were openmp things that I renamed, until I was sure OpenFOAM was ok.  For instance, I renamed libomp.dylib to not-libomp.dylib.  No other issues found with brew doctor.  

About the only weird thing I did the other day was to reboot my MBPro M3, and I think I forgot to close the OpenFOAM volume.  Since that time, (and a perhaps unrelated? Paraview freeze) stuff has been broken.

Honestly don't know how to recover from this.  Would a forced reinstall of openfoam-app help?  Don't want to do anything that may erase clues, or screw things up.  I'm a relatively new Mac user, but have been using Linux for several decades.  Still not really up to speed with the Mac, so some of this is quite confusing.  Apologies about the weird formatting in my post above.  Had no idea it would look like that!

**Comment by gerlero** [comment]
@bdlabitt It's working just fine for me. Did/can you try a reinstall of OpenFOAM.app (``brew reinstall openfoam2306``)?

**Comment by bdlabitt** [comment]
Was working fine for me for a while as well, but something got damaged apparently.  I can try a reinstall.  Should I also add the --no-quarantine  flag to the reinstall?  Kind of a newbie to homebrew (and Mac).  Thanks for your help.

**Comment by gerlero** [comment]
That’s right, you can add the flag to the reinstall command.

**Comment by bdlabitt** [comment]
Reinstall seemed to go ok, I think.  I can open the volume now.

Have some issues with CfdOF on FreeCAD, however.  cfmesh-cfdof and HiSA are refusing to build correctly.  Think we can close this issue, as those shouldn't be your issues.

I'm a little confused though.  Does this openfoam app install create /Volumes/OpenFOAM-v2306 ?  Or does it create 
/Volumes/OpenFOAM-v2306 and /users/me/OpenFOAM/me-v2306 ?  I'm thinking the former.  

Perhaps the CfdOF is creating the other one as a staging area and then puts stuff in /Volumes/OpenFOAM-v2306 when the build is complete.  I'll have to ask the other project's author.

**Comment by gerlero** [comment]
> Have some issues with CfdOF on FreeCAD, however. cfmesh-cfdof and HiSA are refusing to build correctly. Think we can close this issue, as those shouldn't be your issues.

Yes. I can't really help with CfdOF as I'm not familiar with that tool.

> I'm a little confused though. Does this openfoam app install create /Volumes/OpenFOAM-v2306 ? Or does it create
/Volumes/OpenFOAM-v2306 and /users/me/OpenFOAM/me-v2306 ? I'm thinking the former.

Correct; only the former. The latter is used by OpenFOAM itself, and is usually created by third-party extensions to OpenFOAM
