### ISSUE TITLE
Parallel snappyHexMesh with ptscotch failure

### ISSUE THREAD

**Issue by gerlero** [gerlero/openfoam-app#7]
e.g. ~~`$FOAM_TUTORIALS/mesh/snappyHexMesh/motorBike`~~ `$FOAM_TUTORIALS/incompressible/pisoFoam/LES/motorBike/motorBike` case.

https://github.com/BrushXue/OpenFOAM-AppleM1/issues/2, https://github.com/apjanke/homebrew-openfoam/issues/5.

**Comment by BrushXue** [comment]
Is it convenient for you to re-generate the pt-scotch error message from OpenFOAM?

**Comment by gerlero** [comment]
I pointed at the wrong case. The one that consistently fails on my machine is `$FOAM_TUTORIALS/Volumes/OpenFOAM-v2112/tutorials/incompressible/pisoFoam/LES/motorBike/motorBike`. With https://github.com/Homebrew/homebrew-core/pull/95320, it works okay.

@BrushXue sure:

```
[warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[4] #0  [MacBook-Air-de-Gabriel:31698] *** An error occurred in MPI_Alltoallv
[MacBook-Air-de-Gabriel:31698] *** reported by process [2466447361,6]
[MacBook-Air-de-Gabriel:31698] *** on communicator MPI_COMM_WORLD
[MacBook-Air-de-Gabriel:31698] *** MPI_ERR_TRUNCATE: message truncated
[MacBook-Air-de-Gabriel:31698] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[MacBook-Air-de-Gabriel:31698] ***    and potentially your MPI job)
Foam::error::printStack(Foam::Ostream&) in /Volumes/OpenFOAM-v2112/platforms/darwin64ClangDPInt32Opt/lib/libOpenFOAM.dylib
[4] #1  Foam::sigSegv::sigHandler(int) in /Volumes/OpenFOAM-v2112/platforms/darwin64ClangDPInt32Opt/lib/libOpenFOAM.dylib
[4] #2  _sigtramp
```

I attached the full log. Note that sometimes it doesn't fail with an error but seems to deadlock.

[log.snappyHexMesh.zip](https://github.com/gerlero/openfoam2112-app/files/8092190/log.snappyHexMesh.zip)

**Comment by BrushXue** [comment]
Very interesting. I saw different error message when I was using scotch v6, which helped me located the problem directly.
```
Cells per refinement level:
    0	1267
    1	87
    2	136
(4): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(5): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(6): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(7): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(0): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(1): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(2): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
(3): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
```
while scotch v7 just stays at this line forever:
```
Cells per refinement level:
    0	1267
    1	87
    2	136
```

**Comment by BrushXue** [comment]
I was checking the documentation
> the MPI library must support the MPI_THREAD_MULTIPLE level
```
ompi_info | grep -i MPI_THREAD_MULTIPLE
          Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
```
> you will have to initialize your communication subsystem by using the MPI_Init_thread() MPI call instead of MPI_Init()

https://develop.openfoam.com/Development/openfoam/-/blob/master/src/Pstream/mpi/UPstream.C#L233

> and the provided thread support level value returned by the routine must be checked carefully to assert it is indeed MPI_THREAD_MULTIPLE.

Any idea how to verify that?

**Comment by BrushXue** [comment]
Would you like to create a homebrew tap for scotch v6.1.3? If you stay in v6, you don't need to maintain it.

**Comment by gerlero** [comment]
I'm thinking I should give it a different name and make it keg-only to avoid any conflicts with Homebrew's  `scotch`...

**Comment by gerlero** [comment]
Well, I've accidentally reintroduced this issue to main (via #141) while preparing the next release (luckily, I though of testing this case caught it before any broken releases were made). So:

- I need to fix this one again (I'd like to keep Scotch 7—might have to update the custom formula or make a new one)
- Need some kind of smoke test for this issue (something different than `motorBike` because it runs too long), to avoid reintroducing it again
- @BrushXue, if you're still interested, do you think a new push for dropping the offending build flag at homebrew/core might be warranted? We'd need to go in with more solid arguments than before, while reminding all of the fact that the [`scotch`](https://formulae.brew.sh/formula/scotch) formula has very few downloads as is. I don't know exactly how Ubuntu and others are building Scotch in a way that doesn't seem to affect OpenFOAM on those other platforms
- Long term and if this remains a problem, an upstream fix should be sought

**Comment by gerlero** [comment]
Meanwhile, I investigated a little more. 

**It's likely that is is an OpenFOAM bug**, as changing the lines https://develop.openfoam.com/Development/openfoam/-/blob/868d6dd77875772f81fb4277359ecd32e99cdd2a/src/Pstream/mpi/UPstream.C#L226-L230 so as to force this call to `MPI_Init_thread()` to always pass `MPI_THREAD_MULTIPLE` seems to fix the problem with the otherwise broken/hanging `motorBike` case.

I didn't have time to trace it further.

**Comment by BrushXue** [comment]
I think it's a historical problem. OpenMPI didn't support `MPI_THREAD_MULTIPLE` really well when the code was written. Now it should be OK (at least on a single Mac):
```
$ ompi_info | grep "Thread support"
Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
```
But I still prefer scotch 6 unless all tutorial cases can be executed with your proposed change.

**Comment by gerlero** [comment]
Thanks. I'm pushing back any major changes here for now and have reverted to Scotch 6 (via `scotch-no-pthread`).

Given what I know now, I'd like to see this problem dealt with in OpenFOAM (ideally, so that it works with both Scotch 6 & 7 with multithreading support enabled).

@BrushXue Do we have an upstream issue for this? I can't find anything in the OpenFOAM bug tracker.

**Comment by BrushXue** [comment]
Probably because homebrew is the only package manager that is so aggressive... If any major linux distro upgrades to scotch 7 there will be some bug report.

**Comment by gerlero** [comment]
I went ahead and raised the issue at: https://develop.openfoam.com/Development/openfoam/-/issues/2791

**Comment by olesenm** [comment]
For OpenFOAM-v2306, can force use of MPI threads with the `-mpi-threads` option (as a workaround). However, as mentioned in the [issue 2791](https://develop.openfoam.com/Development/openfoam/-/issues/2791) this will also be associated with a general slowdown.
We need to examine how the threads are being used within OpenFOAM itself, but should be able to use MPI_THREAD_FUNNELED or MPI_THREAD_SERIALIZED since we don't actually need to call MPI from different threads simultaneously.

Reading the relevant scotch [INSTALL.txt information](https://gitlab.inria.fr/scotch/scotch/-/blob/master/INSTALL.txt#L525), they state the following:
>Note also that since PT-Scotch calls Scotch routines when operating on a single process, setting "-DSCOTCH_PTHREAD" but not -DSCOTCH_PTHREAD_MPI" will still allow multiple threads to be used on each MPI process, without interfering with MPI itself. In this case, the MPI thread level MPI_THREAD_FUNNELED will be sufficient.

So based on that information, I don't see why ptscotch should be compiled with -DSCOTCH_PTHREAD_MPI at all.

**Comment by gerlero** [comment]
> For OpenFOAM-v2306, can force use of MPI threads with the `-mpi-threads` option (as a workaround). However, as mentioned in the [issue 2791](https://develop.openfoam.com/Development/openfoam/-/issues/2791) this will also be associated with a general slowdown.

Thanks for following up on this here. Is there a configuration or env variable to force this option?

I have decided to keep using my custom built `scotch_no_pthread` (which is also currently at major version 6) for this project at least in the short term.

Still, a future change to a default-built `scotch` might be viable if there's a way to enable `-mpi-threads` globally at the project level (and keeping in mind the possible impact on performance).

> So based on that information, I don't see why ptscotch should be compiled with -DSCOTCH_PTHREAD_MPI at all.

"Note to packagers" at the bottom of that file:

```
6) Note to packagers
====================

Unlike for the v6.1 and earlier branches, Scotch v7.0 now handles
threads dynamically at run time. Packagers have to decide whether to
compile it with threads enabled or not. Based on the current processor
market, we recommend to compile it with "-DCOMMON_PTHREAD" and
"-DSCOTCH_PTHREAD" enabled (and with "-DCOMMON_PTHREAD_AFFINITY_LINUX"
whenever possible). The penalty for single-threaded CPUs will be
minimal, while hyper-threaded and many-core CPUs will benefit from the
multi-threaded algorithms. Packagers that do not want to activate
threads by default can set the compilation flag
"-DSCOTCH_PTHREAD_NUMBER=1", so that only one thread will be used at
run time by default (hence resorting to the sequential algorithms)
unless explicitly decided by the user by way of the
SCOTCH_PTHREAD_NUMBER environment variable.

Also, when the MPI implementation supports it, we recommend to compile
Scotch with the -DMPI_THREAD_MULTIPLE environment variable set, to
benefit from added performance when several threads are available per
MPI process.
```

**Comment by gerlero** [comment]
That is, unless your interpretation of that is that dropping `-DSCOTCH_PTHREAD_MPI` is fine under those recommendations?

I notice that that flag is not explicitly mentioned there, and I'm not sure how all the options they mention here would interact with its presence or lack thereof.

As mentioned in issue 2791, Debian seems to [think it should be enabled](https://www.mail-archive.com/debian-devel-changes@lists.debian.org/msg733635.html):

```
Changes:
 scotch (7.0.1-1exp1) experimental; urgency=medium
 .
   * Team upload.
   * New upstream release.
     - drops scotchparmetisv5 (it was added to 7.0.0 by mistake)
       Only scotchparmetisv3 is provided for parmetis emulation.
     - now provides cmake build, so override dh_auto_configure
       to keep existing direct Makefile builds with Makefile.inc
   * use "set -e" in debian/tests to catch segfaults in tests
   * add -DSCOTCH_PTHREAD_MPI to build flags, as recommended upstream
     Closes: #1003079.
```

If you do have a different interpretation on this and/or we can come up with a well-founded general justification for why that flag should be dropped, that'd help make a more solid case to Homebrew to ask for a change in their default build options. The same case could be made to upstream and/or other packagers.

**Comment by olesenm** [comment]
> Thanks for following up on this here. Is there a configuration or env variable to force this option?

Currently only available as a command-line option. This allows a workaround so that people get somehow work, but the performance issues as so bad that we don't really want to encourage its use.  Will need to revisit after the next release. Will probably also need to involve the scotch developer to have a coherent approach.

Perhaps adding in a `MPI_Query_thread()` within scotch and then have runtime switching of the algorithms.

**Comment by gerlero** [comment]
Sounds reasonable. I can keep everything working as is while waiting for an upstream solution or guidance.

**Comment by gerlero** [comment]
OpenFOAM.app 1.13.0 is now out using default Scotch 7.0.4 from Homebrew.
