### ISSUE TITLE
copy tutorial case

### ISSUE THREAD

**Issue by xuhuizhou-vt** [gerlero/openfoam-app#90]
Thanks! This is a very good tutorial. My question is how can I copy a tutorial case from the Volume/openfoam:2206. I cannot visit the folder after I enter the openfoam enviornment.

**Comment by gerlero** [comment]
I'm not sure I fully understand your problem.

When the OpenFOAM environment is active, the tutorials are available in the directory `$FOAM_TUTORIALS`, which for v2206 translates to `/Volumes/OpenFOAM-v2206/tutorials`. This directory is accessible from either the Finder (where `OpenFOAM-v2206` should show up as a disk) or the command line.

For example, to copy the `pitzDaily` tutorial to your home directory (`~`) from the command line:

```bash
cp -r $FOAM_TUTORIALS/incompressible/simpleFoam/pitzDaily ~/
```

And then you can run it from there:

```bash
cd ~/pitzDaily
simpleFoam
```

Does this solve your issue?

**Comment by xuhuizhou-vt** [comment]
Thanks a lot! I guess I did something wrong before. Now I installed it by manually downloading and installing, and it works. I believe it also works for brew installing.

**Comment by gerlero** [comment]
You're welcome.
